#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GuestbookBirthdayParty.Droid.Resource", IsApplication=true)]

namespace GuestbookBirthdayParty.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::GuestbookBirthdayParty.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::GuestbookBirthdayParty.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::GuestbookBirthdayParty.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::GuestbookBirthdayParty.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::GuestbookBirthdayParty.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::GuestbookBirthdayParty.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::GuestbookBirthdayParty.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::GuestbookBirthdayParty.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::GuestbookBirthdayParty.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::GuestbookBirthdayParty.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.ApplicationName = global::GuestbookBirthdayParty.Droid.Resource.String.ApplicationName;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.Hello = global::GuestbookBirthdayParty.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::GuestbookBirthdayParty.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::GuestbookBirthdayParty.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int clickme = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int howmuch1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int howmuch2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int howmuch3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int howmuch4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int howmuch5 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_chalksmileys_01 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_chalksmileys_02 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_chalksmileys_03 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_chalksmileys_04 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_chalksmileys_05 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int negative02 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int negative03 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int negative04 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int negative05 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int positive01 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int positive02 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int positive03 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int positive04 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int positive05 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int selfie2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int send = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int splashscreen = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MvvmCrossTagId = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MvxBindingTagUnique = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int fifthAnswer = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int firstAnswer = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int firstQuestionHeadline = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int firstQuestionSubheadline = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int fourthAnswer = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int imageView1 = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int secondAnswer = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int secondQuestionBHeadline = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int secondQuestionBSubHeadline = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int secondQuestionHeadline = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int secondQuestionSubHeadline = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int sendButton = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int startMe = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int takeThePictureButton = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int thirdAnswer = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Answer_Item = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FinishView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int FirstQuestionView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int FirstView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int FourthQuestionView = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int SecondQuestionView = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int SplashScreen = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int StatsView = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ThirdQuestionView = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int openCamera = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
